apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.deployment.port }}
    nodePort: {{ .Values.service.nodePort}}
  selector:
    app: {{ .Values.name }}
